use_frameworks!

target 'TimeAPI_Example' do
  platform :ios, '10.0'
  pod 'TimeAPI', :path => '../'

  target 'TimeAPI_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

target 'TimeAPI_macOS_Example' do
    platform :osx, '10.14'
    pod 'TimeAPI', :path => '../'
end
